### ISSUE TITLE
Lab 10: Connect to source issue

### ISSUE THREAD

**Issue by afelix-95** [MicrosoftLearning/mslearn-postgresql#11]
# Module: 00
#### Step: 04

Description of issue

After importing the users and roles from the local server to the flexible server, I could not connect to source when creating the Migration project in the Azure Portal. I tried using both the postgres superuser and the pgadmin user created without a superuser role but both options return an error `Failed to connect to server : Authentication failed. The provided password is incorrect. Please confirm it and try again`. I've triple checked the passwords and they both work when connecting locally to the database, so I'm sure they're correctly typed in the configuration step.

Repro steps:

![Screenshot 2024-05-03 132149](https://github.com/MicrosoftLearning/mslearn-postgresql/assets/148110824/eae900cc-d34b-4f23-9349-cb8aea3245ca)

**Comment by HeyMo0sh** [comment]
If you are doing it with Azure VM then the public network NSG needs to be set up.
Have you setup the local postgresql instance to be configured to listen for hosts which are not local?

If those work for you then I will write that up - the password not correct when it is says to me that there is something blocking communication from Migrate PostgreSQL to Azure Database for PostgreSQL Flexible Server

**Comment by HeyMo0sh** [comment]
You have localhost as the server name. The source server has to be accessible to the flexible server, i.e. it has to be accessible from the internet.

So you have to allow your IP address and port 5432 open. Azure won't be able to resolve localhost.
I will document this.

**Comment by afelix-95** [comment]
I am testing it outside of VM environment.
I checked the `postgresql.conf` file and its parameter `listen_addresses` was already set to `'*'`. 
In the `pg_hba.conf` file, I added the following line:
```
host    all    all    0.0.0.0/0    md5
```
I have also added Firewall rules for port 5432.
After that, I restarted the server and tried connecting to it again using the server's public IP address instead of localhost.
Now the error that I'm getting is:
```
Failed to connect to server : The operation has timed out.
```

**Comment by HeyMo0sh** [comment]
Are you able to connect to your database from say another Azure VM? you can either telnet to <your ip address> 5432 or using powershell:

 Test-NetConnection -ComputerName <your IP address> -Port 5432 -InformationLevel "Detailed" 
 
 I found I had to set up a NSG for port 5432 on the VM and also do windows firewall on the VM itself

**Comment by afelix-95** [comment]
One more thing, in the instructions for **Create Database Migration Project in Azure Database for PostgreSQL Flexible Server**, step 5 you reference user as `demo` and its password as `Pa$$w0rd` for the target server but in this case it should be `pgAdmin` and the random password generated at the beginning of the lab instructions.

**Comment by HeyMo0sh** [comment]
Thanks for spotting that - I have corrected it and pushed to https://github.com/MicrosoftLearning/mslearn-postgresql/pull/13
