### ISSUE TITLE
Lab 11: Connect to source issue - Online Migration Wizard

### ISSUE THREAD

**Issue by afelix-95** [MicrosoftLearning/mslearn-postgresql#12]
# Module: 00
#### Step: 04

Description of issue

When trying to connect to the local server I receive an error message:
```
Error type

    Failed to connect, please check error details

Error Detail
    Connection failed.
    Exception while connecting
    No connection could be made because the target machine actively refused it
```
I have created a Firewall outbound rule for the used port (5433 in this case because the default 5432 is being used by PostgreSQL 16 while I'm doing this lab with PostgreSQL 14) and enabled TLS security protocol in the  `postgresql.conf` file, but I still can't establish a connection. I have also managed to import the database schema from the source database to the flexible server.

Repro steps:

![Screenshot 2024-05-03 151020](https://github.com/MicrosoftLearning/mslearn-postgresql/assets/148110824/1e766615-3097-40d0-8b99-1d58d4f6611c)

**Comment by HeyMo0sh** [comment]
I have a new exercise for 11. So will be pushing that up Monday which hopefully resolves this as online migration is not fully supported right now from local instance:

https://learn.microsoft.com/en-us/azure/postgresql/migrate/migration-service/concepts-migration-service-postgresql#how-to-migrate-to-azure-database-for-postgresql-flexible-server

So this exercise is wrong right now

**Comment by afelix-95** [comment]
I went through the new exercise and it works without problems. Closing this issue now.
