### ISSUE TITLE
Lab 4: Task 'Create the zoo database' out of order?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/mslearn-postgresql#15]
# Module: 00
#### Step: 00

Description of issue

In Instructions file https://github.com/MicrosoftLearning/mslearn-postgresql/blob/main/Instructions/Labs/04-exercise-configure-permissions.md, the Task 'Create the zoo database' looks like it might be out-of-order:  It probably makes more sense to move it from where it is currently, and place it just after the Task 'Connect to Azure Database for PostgreSQL flexible server', since that task gives the basics for login/connect to DB.  

After that task, the 'Create the zoo database' would make perfect sense, and flow well.

**Comment by MScalopez** [comment]
Reviewing Bug

**Comment by MScalopez** [comment]
Very good suggestion, I have updated the order of the steps.  Thank you.
